### ISSUE TITLE
NUnit duration and TestRun status

### ISSUE THREAD

**Issue by siposaron** [test-results-reporter/parser#63] opened 2024-05-02 15:15 UTC
https://docs.nunit.org/articles/nunit/technical-notes/usage/Test-Result-XML-Format.html

The NUnit v3 format does not have `time` property, but it has `duration`. Current version 0.1.14 does not parse the duration as per NUnit specifications.

i.e. 
`<test-run id="0" runstate="Runnable" testcasecount="40" result="Passed" total="6" passed="6" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="10" engine-version="3.15" clr-version="4.0" start-time="2024-03-21 13:00:15Z" end-time="2024-03-21 13:00:42Z" duration="26.189586">`

Another thing, the test-run `Passed` status is parsed to `FAIL`.

**Comment by bryanbcook** [comment] 2024-05-28 16:28
Confirmed regarding the `duration` property -- the nunit-v3.xml sample used in the test suite has some omissions. I'll investigate.

**Comment by bryanbcook** [comment] 2024-05-28 19:07
There's a disconnect between the sample formats provided by the NUnit team and the actual output.

This [document](https://docs.nunit.org/articles/nunit/technical-notes/usage/XML-Formats.html) refers to the following sample files, which our tests are based on:

* https://nunit.org/files/testresult_25.txt
* https://nunit.org/files/testresult_30.txt

`duration`/`time` seems to be the most glaring difference and I can apply a fix between v2/v3 versions.

Good catch on the top-level test-run status. It's currently not being mapped which results in a FAIL.

**Comment by ASaiAnudeep** [comment] 2024-05-29 04:41
Fix released in - [v0.1.18](https://github.com/test-results-reporter/parser/releases/tag/v0.1.18)

**Closed by ASaiAnudeep** 2024-05-29 04:41 UTC
